output "info" {
  description = "a whole bag of data passed back to tfs_compute module..."
  value = {
    # instance_config = local.default_instance_config.I
    # II = local.default_instance_config.II
    nic_name                         = local.default_instance_config.nic_name
    ip_name                          = local.default_instance_config.ip_name
    private_ip_address_alloc         = local.default_instance_config.private_ip_address_alloc
    vm_name                          = local.default_instance_config.vm_name
    vm_size                          = local.default_instance_config.vm_size
    vm_pass                          = local.default_instance_config.vm_pass
    disk_caching                     = local.default_instance_config.disk_caching
    disk_strg_acc_type               = local.default_instance_config.disk_strg_acc_type
    publisher                        = local.default_instance_config.publisher
    offer                            = local.default_instance_config.offer
    sku                              = local.default_instance_config.sku
    version                          = local.default_instance_config.version
    enable_vm_availability_set       = local.default_instance_config.enable_vm_availability_set
    platform_fault_domain_count      = local.default_instance_config.platform_fault_domain_count
    platform_update_domain_count     = local.default_instance_config.platform_update_domain_count
    enable_proximity_placement_group = local.default_instance_config.enable_proximity_placement_group
    data_disk_name                   = local.default_instance_config.data_disk_name
    resource_group_location          = local.default_instance_config.resource_group_location
    data_disk_storage_acc_type       = local.default_instance_config.data_disk_storage_acc_type
    disk_size_gb                     = local.default_instance_config.disk_size_gb
    enable_encryption_at_host        = local.default_instance_config.enable_encryption_at_host
    vm_availability_zone             = local.default_instance_config.vm_availability_zone
    instances_count                  = local.default_instance_config.instances_count
    disable_password_authentication  = local.default_instance_config.disable_password_authentication
    admin_username                   = local.default_instance_config.admin_username
    admin_ssh_key_data               = local.default_instance_config.admin_ssh_key_data
    enable_boot_diagnostics          = local.default_instance_config.enable_boot_diagnostics
    storage_account_name             = local.default_instance_config.storage_account_name
    storage_account_uri              = local.default_instance_config.storage_account_uri
    pvt_dns_zone_name                = local.default_instance_config.pvt_dns_zone_name
    pvt_rg_name                      = local.default_instance_config.pvt_rg_name
    data_disk_lun                    = local.default_instance_config.data_disk_lun
    caching_type                     = local.default_instance_config.caching_type
    tags                             = local.default_instance_config.tags
  }
}
